spring:
  application:
    name: jobtracker

  datasource:
    url: jdbc:postgresql://localhost:5432/jobtracker
    username: jobtracker
    password: jobtracker

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: ${JWT_SECRET}
  expiration: 1800000

